echo '{"a": 7}' | jq '.a + 1'
echo '{"a": [1,2], "b": [3,4]}' | jq '.a + .b'
echo '{"a": 7}' | jq '.a + null'
echo '{}' | jq '.a + 1'
echo 'null' | jq '{a: 1} + {b: 2} + {c: 3} + {a: 42}'
echo '{"a":3}' | jq '4 - .a'
echo '["xml", "yaml", "json"]' | jq '. - ["xml", "yaml"]'
echo '5' | jq '10 / . * 3'
echo '{"k": {"a": 1, "b": 2, "c": 3}}' | jq '{"k": {"a": 1, "b": 2}} * {"k": {"a": 0,"c": 3}}'
echo '[[1,2], "string", {"a":2}, null, -5]' | jq '.[] | length'
echo '[[0,1], ["a","b","c"]]' | jq 'map(has(2))'
echo '[1,5,3,0,7]' | jq 'map(select(. >= 2))' 
echo '[{"foo":1,"bar":14}, {"foo":2, "bar":3}]' | jq 'max_by(.foo)'
