echo '{"foo": 42, "bar": "less interesting data"}' | jq '.foo?'
echo '{"notfoo": 42, "alsonotfoo": "less interesting data"}' | jq '.foo?'
echo '{"foo": 42}' | jq '.["foo"]?'
echo '[1,2]' | jq '[.foo?]'
echo '{"foo": 42, "bar": "less interesting data"}' | jq '.["foo"]'
echo '[{"name": "JSON", "good":true}, {"name":"XML", "good":false}]' | jq '.[0]'
echo '[{"name": "JSON", "good":true}, {"name":"XML", "good":false}]' | jq '.[2]'
echo '[1,2,3]' | jq '.[-1]'
echo '[1,2,3]' | jq '.[-2]'
echo '[1,2,3]' | jq '.[-3]'
echo '["a", "b", "c", "d", "e"]' | jq '.[2:4]'
echo '"abcde"' | jq '.[2:4]'
echo '["a", "b", "c", "d", "e"]' | jq '.[:3]'
echo '["a", "b", "c", "d", "e"]' | jq '.[-2:]'
echo '[{"name":"JSON", "good":true}, {"name":"XML", "good":false}]' | jq '.[]'
echo '[]' | jq '.[]'
echo '{"foo":[1,2,3]}' | jq '.foo[]'
echo '{"a":1, "b":1}' | jq '.[]'
echo '{"foo":42, "bar": "something else", "baz": true}' | jq '.foo, .bar'
echo '{"user":"stedolan", "projects": ["jq", "wikiflow"]}' | jq '.user, .projects[]'
echo '["a", "b", "c", "d", "e"]' | jq '.[4,2,1]'
echo '[{"name": "JSON", "good":true}, {"name":"XML", "good":false}]' | jq '.[] | .name'
echo 1 | jq '(. + 2) * 5'
